apiVersion: 1
groups:
  - name: alert-evaluation-group
    folder: alerts
    interval: 1m
    rules:
      - title: Slack Alert Channel
        condition: C
        data:
          - refId: A
            datasourceUid: eekctvmyci5fkf
            model:
              expr: http_requests_total
              instant: true
          - refId: C
            model:
              conditions:
                - evaluator:
                    params:
                      - 250
                    type: gt
                  reducer:
                    type: last
              expression: A
              type: threshold
        for: 1m
        annotations:
          runbook_url: ${SLACK_WEBHOOK_URL}
